std_noise_train: 0.05
std_noise: 0.1
components_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 50, 100]
layers_list: [1, 20]
n_rep_list: [1, 20, 50, 100]
denoiser_type_list: ["AD"]
pth_kernel: "blur_models/blur_1.mat" #"blur_models/blur_1.mat"
img_list: [0, 4]
n_iter_per_lambda: 50
n_lambda: 50
lambda_start: 10
lambda_end: 1e-5
eps_stop: 1e-5
warm_restart: true
save_path: "experiments/deblurring_analysis_stop_1e-5/results.pkl"