std_noise_train: 0.05
std_noise: 0.05
kernel_size: 16
components_list: [50] #[2, 10, 50] #[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 50, 100]
layers_list: [1] #[1, 20]
n_rep_list: [1, 2, 10, 100, 500] #[1, 20, 50, 100]
denoiser_type_list: ["SD"] #, "SD"]
pth_kernel: "blur_models/blur_3.mat" #"blur_models/blur_1.mat"
img_list: [0] #, 4]
lambdas: [1e-1, 1e-2] #, 1e-3] #, 1e-5, 1e-6]
iter_final: 1000
save_path: "convergence/SD_16K_50C_1L/results.pkl"