std_noise_train: 0.05
std_noise: 0.1
components_list: [2, 5, 10, 20, 100]
layers_list: [1, 20]
n_rep_list: [1, 20, 100]
denoiser_type_list: ["SD"]
pth_kernel: "blur_models/blur_1.mat"
img_list: [0] #, 4]
n_iter_per_lambda: 200
n_lambda: 50
lambda_start: 10
lambda_end: 1e-5
eps_stop: 1e-6
warm_restart: true
iter_final: 500
save_path: "experiments/deblurring_synthesis_stop_1e-6_ista_fista/results.pkl"