std_noise_train: 0.05
std_noise: 0.1
components_list: [2, 20] #, 3, 4, 5, 6, 7, 8, 9, 10, 20, 50, 100]
layers_list: [1]
n_rep_list: [1, 100] #, 50, 100]
denoiser_type_list: ["SD"] #, "SD"]
pth_kernel: "blur_models/blur_1.mat" #"blur_models/blur_1.mat"
img_list: [0]
n_iter_per_lambda: 100
n_lambda: 10
lambda_start: 10
lambda_end: 1e-5
eps_stop: 1e-5
warm_restart: true
iter_final: 500
save_path: "experiments/ista2fista_fista/results.pkl"