std_noise_train: 0.05
std_noise: 0.05
kernel_size: 16
components_list: [50]
layers_list: [1]
n_rep_list: [1, 10, 50, 100]
denoiser_type_list: ["SD"]
prop_mask: 0.7
img_list: [24]
lambdas: [1e-1, 1e-3]
iter_final: 1000
save_path: "convergence_inpainting/SD_16K_50C_1L/results.pkl"