std_noise_train: 0.05
std_noise: 0.05
kernel_size: 5
components_list: [10]
layers_list: [1]
n_rep_list: [100]
denoiser_type_list: ["SD"]
pth_kernel: "blur_models/blur_3.mat"
img_list: [0]
n_lambda: 5
n_iter_per_lambda: 200
eps_stop: null
warm_restart: true
iter_grad: 500
lambda_unbiased: 1e-3
save_path: "convergence/SD_10C_1L_unbiased/results_optimal_lambda.pkl"