std_noise_train: 0.05
std_noise: 0.3
components_list: [1, 10, 50] #, 10] #, 3, 5, 10, 20, 50, 100]
layers_list: [1, 20] #, 20] #, 20]
n_rep_list: [1, 20, 50, 100]
denoiser_type_list: ["AD"]
pth_kernel: "blur_models/no_blur.mat" #"blur_models/blur_1.mat"
img_list: [4] #[0]
n_iter_per_lambda: 1
n_lambda: 50
lambda_start: 10
lambda_end: 1e-5
eps_stop: null
warm_restart: false
save_path: "experiments/denoising_03_no_warm_restart/results.pkl"